### ISSUE TITLE
Error with cents (USD)

### ISSUE THREAD

**Issue by jcamilovallejos** [kwn/number-to-words#139]
I am trying to convert money to words. But I don't know what happen with this number: 584.93 The library show me: Five Hundred Eighty-Four Dollars Ninety-Two Cents.

```
use NumberToWords\NumberToWords;
$numberToWords = new NumberToWords();
$currencyTransformer = $numberToWords->getCurrencyTransformer('en')->toWords(584.93*100, 'USD');
echo $currencyTransformer;
```

It is not ninety-two. It is ninety-three. Why does this happen?

**Comment by kwn** [comment]
It's because floating point numbers arithmetics and its limited precision. You should never use floating point to represent any monetary values.

https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate
https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency
