### ISSUE TITLE
Represent cents as NUMBERS Format

### ISSUE THREAD

**Issue by popovsergiy** [kwn/number-to-words#8]
I need to have next output "pięćdziesiąt złotych 98 groszy". 
I try use this library as describe in README and get next result "piecdziesiat zlotych 98/100"
```php
$registry = new \Kwn\NumberToWords\Transformer\TransformerFactoriesRegistry([
	new \Kwn\NumberToWords\Language\Polish\TransformerFactory()
]);
$numberToWords = new \Kwn\NumberToWords\NumberToWords($registry);
$currencyTransformer = $numberToWords->getCurrencyTransformer('pl', 'PLN', \Kwn\NumberToWords\Model\SubunitFormat::NUMBERS);
var_dump($currencyTransformer->toWords(50.98)); 
// piecdziesiat zlotych 98/100
```
What does actually mean this "98/100"?

P.S. I has added support for Ukrainian and Russian languages but before to do PR I want understand how to implement this feature in correct way.

**Comment by kwn** [comment]
Hi @popovsergiy 

So currently there are two representations of subunits. One of them is an expanded version:
```
\Kwn\NumberToWords\Model\SubunitFormat::WORDS: 50.98 ---> pięćdziesiąt złotych dziewięćdziesiąt osiem groszy
```

Another one is a short version:
```
\Kwn\NumberToWords\Model\SubunitFormat::NUMBERS: 50.98 ---> pięćdziesiąt złotych 98/100
```

The meaning of a shorter version is just to represent a fracition (98 groszy of a 1 złoty) where 1 złoty = 100 groszy

From what I understand, you need to use some kind of "mixed" representation - numbers with subunit name. You've got two possibilities now. You can try to change a business requirements in your project, and use `SubunitFormat::WORDS` (fully expanded subunits translation), or you can create a PR which adds another subunits representation - `SubunitFormat::NUMBERS_WORDS` which allows you to achieve a representation you need (98 groszy).

I'm happy to merge your PR. I hope you'll be able to provide some unit test, because I don't speak Ukrainian nor Russian ;)

**Comment by popovsergiy** [comment]
I see.
Ok, I will create unit tests. 
"Mixed" format is not required but is desirable. If business will require this I add `SubunitFormat::NUMBERS_WORDS`.

**Comment by popovsergiy** [comment]
I has created PR if all is OK tomorrow will create support for Russian.
